#!/usr/bin/env zsh
# vim: ft=zsh

zhiyuan=$HOME/.config/zhiyuan
fpath=( $zhiyuan/zsh/functions $fpath)
autoload -Uz has_cmd backup rich && rich

# 配置pip
if has_cmd pip; then
  std "configuring pip..."
  pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
  pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
fi

# 初始化conda
std "try to init conda"
parent=( $HOME $HOME/program $HOME/software )
conda=( miniconda3 anaconda3 Anaconda3 )
bin="bin/conda"
_break=false
for p in $parent; do
  for c in $conda; do
    b=$p/$c/$bin
    if [[ -f $b ]]; then
      conda_bin=$b
      std "find conda binary: $b"
      $conda_bin init zsh
      _break=true
      break
    fi
  done
  if $_break; then break; fi
done

backup $HOME/.condarc condarc
cat << 'EOF' > $HOME/.condarc
changeps1: False
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
EOF
