#!/usr/bin/env zsh
# vim: ft=zsh

zhiyuan=$HOME/.config/zhiyuan
fpath=( $zhiyuan/zsh/functions $fpath)
autoload -Uz rich && rich

std "try to init texlive"
parent=( /usr/local $HOME/.local )
year=2021
for p in $parent; do
  texlive=$p/texlive
  if [[ -d $texlive ]]; then
    texlive=$texlive/$year
    if [[ -n $texlive ]]; then
      std "find texlive path: $texlive"
      cat << EOF >> $HOME/.zshrc

export PATH=$texlive/bin/x86_64-linux:\$PATH
export MANPATH=$texlive/texmf-dist/doc/man:\$MANPATH
export INFOPATH=$texlive/texmf-dist/doc/info:\$INFOPATH
EOF
      break
    fi
  fi
done
